# The toolchains install their own libc to target. As a consequence, it breaks
# the userland of the distribution!
#
# Sadly, the exernal.mk cannot override these variables as it is included after
# the packages.mk of the buildroot tree. The local.mk is the only alternative
# for now as it included before.
#
# If the variable BR2_PACKAGE_OVERRIDE_FILE is overridden by the .config or
# through the command-line, the target gets polluted!
#
# FIXME: Find a better alternative!
GLIBC_INSTALL_TARGET = NO
MUSL_INSTALL_TARGET = NO
UCLIBC_INSTALL_TARGET = NO
SKELETON_INSTALL_TARGET = NO
SKELETON_INIT_COMMON_INSTALL_TARGET = NO
SKELETON_INIT_NONE_INSTALL_TARGET = NO
SKELETON_INIT_OPENRC_INSTLAL_TARGET = NO
SKELETON_INIT_SYSTEMD_INSTALL_TARGET = NO
SKELETON_INIT_SYSV_INSTALL_TARGET = NO
TOOLCHAIN_EXTERNAL_ARM_AARCH64_BE_INSTALL_TARGET = NO
TOOLCHAIN_EXTERNAL_ARM_AARCH64_INSTALL_TARGET = NO
TOOLCHAIN_EXTERNAL_ARM_ARM_INSTALL_TARGET = NO
TOOLCHAIN_EXTERNAL_BOOTLIN_INSTALL_TARGET = NO
TOOLCHAIN_EXTERNAL_CODESCAPE_IMG_MIPS_INSTALL_TARGET = NO
TOOLCHAIN_EXTERNAL_CODESCAPE_MTI_MIPS_INSTALL_TARGET = NO
TOOLCHAIN_EXTERNAL_CODESOURCERY_AARCH64_INSTALL_TARGET = NO
TOOLCHAIN_EXTERNAL_CODESOURCERY_ARM_INSTALL_TARGET = NO
TOOLCHAIN_EXTERNAL_CODESOURCERY_INSTALL_TARGET = NO
TOOLCHAIN_EXTERNAL_CODESOURCERY_MIPS_INSTALL_TARGET = NO
TOOLCHAIN_EXTERNAL_CUSTOM_INSTALL_TARGET = NO
TOOLCHAIN_EXTERNAL_LINARO_AARCH64_BE_INSTALL_TARGET = NO
TOOLCHAIN_EXTERNAL_LINARO_AARCH64_INSTALL_TARGET = NO
TOOLCHAIN_EXTERNAL_LINARO_ARM_INSTALL_TARGET = NO
TOOLCHAIN_EXTERNAL_LINARO_ARMEB_INSTALL_TARGET = NO
TOOLCHAIN_EXTERNAL_SYNOPSYS_ARC_INSTALL_TARGET = NO
TOOLCHAIN_EXTERNAL_INSTALL_TARGET = NO

ifndef ZSTDCAT
ZSTDCAT = zstdcat
INFLATE.zst = $(ZSTDCAT)
endif
