################################################################################
#
# skeleton-pacstrap
#
################################################################################

SKELETON_PACSTRAP_INSTALL_STAGING = YES

SKELETON_PACSTRAP_DEPENDENCIES = host-arch-install-scripts host-iamroot host-pacman

SKELETON_PACSTRAP_ARCH = $(call qstrip,$(BR2_ARCH))
ifeq ($(BR2_arm),y)
SKELETON_PACSTRAP_ARCH = armv7h
endif

ifeq ($(BR2_PACKAGE_HOST_ARCHLINUX_KEYRING),y)
SKELETON_PACSTRAP_DEPENDENCIES += host-archlinux-keyring
SKELETON_PACSTRAP_KEYRINGS += archlinux
endif
ifeq ($(BR2_PACKAGE_HOST_ARCHLINUX32_KEYRING),y)
SKELETON_PACSTRAP_DEPENDENCIES += host-archlinux32-keyring
SKELETON_PACSTRAP_KEYRINGS += archlinux32
endif
ifeq ($(BR2_PACKAGE_HOST_ARCHLINUXARM_KEYRING),y)
SKELETON_PACSTRAP_DEPENDENCIES += host-archlinuxarm-keyring
SKELETON_PACSTRAP_KEYRINGS += archlinuxarm
endif
ifeq ($(BR2_PACKAGE_HOST_ARCHPOWER_KEYRING),y)
SKELETON_PACSTRAP_DEPENDENCIES += host-archpower-keyring
SKELETON_PACSTRAP_KEYRINGS += archpower
endif
ifeq ($(BR2_PACKAGE_HOST_ARCHLINUXRISCV_KEYRING),y)
SKELETON_PACSTRAP_DEPENDENCIES += host-archlinuxriscv-keyring
SKELETON_PACSTRAP_KEYRINGS += archlinux
endif
ifeq ($(BR2_PACKAGE_HOST_MANJARO_KEYRING),y)
SKELETON_PACSTRAP_DEPENDENCIES += host-manjaro-keyring
SKELETON_PACSTRAP_KEYRINGS += manjaro
endif

SKELETON_PACSTRAP_PACKAGES = $(call qstrip,$(BR2_PACKAGE_SKELETON_PACSTRAP_PACKAGES))
ifeq ($(SKELETON_PACSTRAP_PACKAGES),)
SKELETON_PACSTRAP_PACKAGES = base
endif

ifeq ($(BR2_PACKAGE_SKELETON_PACSTRAP_ARCHLINUXARM_ARMV7H_CONFIGURATION_FILE),y)
SKELETON_PACSTRAP_CONFIGURATION_FILE = $(SKELETON_PACSTRAP_PKGDIR)/archlinuxarm_armv7h_pacman.conf
endif
ifeq ($(BR2_PACKAGE_SKELETON_PACSTRAP_ARCHLINUXARM_AARCH64_CONFIGURATION_FILE),y)
SKELETON_PACSTRAP_CONFIGURATION_FILE = $(SKELETON_PACSTRAP_PKGDIR)/archlinuxarm_aarch64_pacman.conf
endif
ifeq ($(BR2_PACKAGE_SKELETON_PACSTRAP_MANJAROARM_STABLE_AARCH64_CONFIGURATION_FILE),y)
SKELETON_PACSTRAP_CONFIGURATION_FILE = $(SKELETON_PACSTRAP_PKGDIR)/manjaroarm-stable_aarch64_pacman.conf
endif
ifeq ($(BR2_PACKAGE_SKELETON_PACSTRAP_MANJAROARM_UNSTABLE_AARCH64_CONFIGURATION_FILE),y)
SKELETON_PACSTRAP_CONFIGURATION_FILE = $(SKELETON_PACSTRAP_PKGDIR)/manjaroarm-unstable_aarch64_pacman.conf
endif
ifeq ($(BR2_PACKAGE_SKELETON_PACSTRAP_ARCHPOWER_POWERPC64_CONFIGURATION_FILE),y)
SKELETON_PACSTRAP_CONFIGURATION_FILE = $(SKELETON_PACSTRAP_PKGDIR)/archpower_powerpc64_pacman.conf
endif
ifeq ($(BR2_PACKAGE_SKELETON_PACSTRAP_ARCHPOWER_POWERPC64LE_CONFIGURATION_FILE),y)
SKELETON_PACSTRAP_CONFIGURATION_FILE = $(SKELETON_PACSTRAP_PKGDIR)/archpower_powerpc64le_pacman.conf
endif
ifeq ($(BR2_PACKAGE_SKELETON_PACSTRAP_ARCHPOWER_RISCV64_CONFIGURATION_FILE),y)
SKELETON_PACSTRAP_CONFIGURATION_FILE = $(SKELETON_PACSTRAP_PKGDIR)/archpower_riscv64_pacman.conf
endif
ifeq ($(BR2_PACKAGE_SKELETON_PACSTRAP_ARCHLINUXRISCV_RISCV64_CONFIGURATION_FILE),y)
SKELETON_PACSTRAP_CONFIGURATION_FILE = $(SKELETON_PACSTRAP_PKGDIR)/archlinuxriscv_riscv64_pacman.conf
endif
ifeq ($(BR2_PACKAGE_SKELETON_PACSTRAP_ARCHLINUX32_I686_CONFIGURATION_FILE),y)
SKELETON_PACSTRAP_CONFIGURATION_FILE = $(SKELETON_PACSTRAP_PKGDIR)/archlinux32_i686_pacman.conf
endif
ifeq ($(BR2_PACKAGE_SKELETON_PACSTRAP_ARCHLINUX_X86_64_CONFIGURATION_FILE),y)
SKELETON_PACSTRAP_CONFIGURATION_FILE = $(SKELETON_PACSTRAP_PKGDIR)/archlinux_x86_64_pacman.conf
endif
ifeq ($(BR2_PACKAGE_SKELETON_PACSTRAP_MANJARO_STABLE_X86_64_CONFIGURATION_FILE),y)
SKELETON_PACSTRAP_CONFIGURATION_FILE = $(SKELETON_PACSTRAP_PKGDIR)/manjaro-stable_x86_64_pacman.conf
endif
ifeq ($(BR2_PACKAGE_SKELETON_PACSTRAP_MANJARO_UNSTABLE_X86_64_CONFIGURATION_FILE),y)
SKELETON_PACSTRAP_CONFIGURATION_FILE = $(SKELETON_PACSTRAP_PKGDIR)/manjaro-unstable_x86_64_pacman.conf
endif
ifeq ($(BR2_PACKAGE_SKELETON_PACSTRAP_CUSTOM_CONFIGURATION_FILE),y)
SKELETON_PACSTRAP_CONFIGURATION_FILE = $(call qstrip,$(BR2_PACKAGE_SKELETON_PACSTRAP_CUSTOM_CONFIGURATION_FILE_PATH))
ifeq ($(SKELETON_PACSTRAP_CONFIGURATION_FILE),)
$(error No configuration file set. Check your BR2_PACKAGE_SKELETON_PACSTRAP_CUSTOM_CONFIGURATION_FILE_PATH setting)
endif
endif

SKELETON_PACSTRAP_ENV += IAMROOT_DEFLIB=/lib:/usr/lib
SKELETON_PACSTRAP_ENV += IDO_SECURE_PATH=$(HOST_DIR)/bin:/usr/local/bin:/usr/bin:/bin

define SKELETON_PACSTRAP_BUILD_CMDS
	rm -Rf $(O)/gnupg/
	rm -Rf $(@D)/rootfs/
	mkdir -p $(@D)/rootfs/
	$(INSTALL) -D -m 0644 $(SKELETON_PACSTRAP_CONFIGURATION_FILE) $(HOST_DIR)/etc/pacman.conf
	PATH=$(BR_PATH) $(SKELETON_PACSTRAP_ENV) ido --libdir pacman-key --init --gpgdir $(O)/gnupg
	# Fixes:
	#
	#	error: base: signature from "Arch Linux ARM Build System <builder@archlinuxarm.org>" is marginal trust
	#
	printf "marginals-needed 2\n" >>$(O)/gnupg/gpg.conf
	if [ "$(SKELETON_PACSTRAP_KEYRINGS)" ]; then \
		PATH=$(BR_PATH) $(SKELETON_PACSTRAP_ENV) ido --libdir pacman-key --populate $(SKELETON_PACSTRAP_KEYRINGS) --gpgdir $(O)/gnupg; \
	fi
	( cd $(@D) && $(TARGET_MAKE_ENV) $(SKELETON_PACSTRAP_ENV) ido --libdir pacstrap -GMC $(HOST_DIR)/etc/pacman.conf $(@D)/rootfs $(SKELETON_PACSTRAP_PACKAGES) --arch $(SKELETON_PACSTRAP_ARCH) --dbpath $(@D)/rootfs/var/lib/pacman --gpgdir $(O)/gnupg )
endef

define SKELETON_PACSTRAP_INSTALL_TARGET_CMDS
	$(call SYSTEM_RSYNC,$(@D)/rootfs,$(TARGET_DIR))
endef

# For the staging dir, we install nothing, but we need the /lib and /usr/lib
# appropriately setup.
define SKELETON_PACSTRAP_INSTALL_STAGING_CMDS
	$(call SYSTEM_BIN_SBIN_LIB_DIRS,$(STAGING_DIR))
	$(call SYSTEM_USR_SYMLINKS_OR_DIRS,$(STAGING_DIR))
	$(call SYSTEM_LIB_SYMLINK,$(STAGING_DIR))
endef

$(eval $(generic-package))
