################################################################################
#
# skeleton-debootstrap
#
################################################################################

SKELETON_DEBOOTSTRAP_DEPENDENCIES = host-debootstrap host-iamroot

ifeq ($(BR2_arm),y)
SKELETON_DEBOOTSTRAP_ARCH = armel
endif
ifeq ($(BR2_aarch64),y)
SKELETON_DEBOOTSTRAP_ARCH = arm64
endif
ifeq ($(BR2_mips),y)
SKELETON_DEBOOTSTRAP_ARCH = mips
endif
ifeq ($(BR2_mipsel)$(BR2_mips_32r2):$(BR2_MIPS_SOFT_FLOAT),yy:)
SKELETON_DEBOOTSTRAP_ARCH = mipsel
endif
ifeq ($(BR2_mips64el)$(BR2_MIPS_NABI64):$(BR2_MIPS_SOFT_FLOAT),yy:)
SKELETON_DEBOOTSTRAP_ARCH = mips64el
endif
ifeq ($(BR2_powerpc),y)
SKELETON_DEBOOTSTRAP_ARCH = ppc
endif
ifeq ($(BR2_powerpc64le),y)
SKELETON_DEBOOTSTRAP_ARCH = ppc64el
endif
ifeq ($(BR2_s390x),y)
SKELETON_DEBOOTSTRAP_ARCH = s390x
endif
ifeq ($(BR2_i386),y)
SKELETON_DEBOOTSTRAP_ARCH = i386
endif
ifeq ($(BR2_x86_64),y)
SKELETON_DEBOOTSTRAP_ARCH = amd64
endif

ifneq ($(SKELETON_DEBOOTSTRAP_ARCH),)
SKELETON_DEBOOTSTRAP_OPTS += --arch=$(SKELETON_DEBOOTSTRAP_ARCH)
endif
ifeq ($(BR2_PACKAGE_SKELETON_DEBOOTSTRAP_INCLUDE),y)
SKELETON_DEBOOTSTRAP_OPTS += --include=$(call qstrip,$(BR2_PACKAGE_SKELETON_DEBOOTSTRAP_INCLUDE))
endif
ifeq ($(BR2_PACKAGE_SKELETON_DEBOOTSTRAP_EXCLUDE),y)
SKELETON_DEBOOTSTRAP_OPTS += --exclude=$(call qstrip,$(BR2_PACKAGE_SKELETON_DEBOOTSTRAP_EXCLUDE))
endif
ifeq ($(BR2_PACKAGE_SKELETON_DEBOOTSTRAP_EXTRA_SUITES),y)
SKELETON_DEBOOTSTRAP_OPTS += --extra-suites=$(call qstrip,$(BR2_PACKAGE_SKELETON_DEBOOTSTRAP_EXTRA_SUITES))
endif
ifeq ($(BR2_PACKAGE_SKELETON_DEBOOTSTRAP_COMPONENTS),y)
SKELETON_DEBOOTSTRAP_OPTS += --components=$(call qstrip,$(BR2_PACKAGE_SKELETON_DEBOOTSTRAP_COMPONENTS))
endif
ifeq ($(BR2_PACKAGE_SKELETON_DEBOOTSTRAP_MERGED_USR),y)
SKELETON_DEBOOTSTRAP_OPTS += --merged-usr
else
SKELETON_DEBOOTSTRAP_OPTS += --no-merged-usr
endif

ifeq ($(BR2_PACKAGE_SKELETON_DEBOOTSTRAP_DEBIAN_12_BOOKWORM_SUITE),y)
SKELETON_DEBOOTSTRAP_SUITE = bookworm
endif
ifeq ($(BR2_PACKAGE_SKELETON_DEBOOTSTRAP_DEBIAN_11_BULLSEYE_SUITE),y)
SKELETON_DEBOOTSTRAP_SUITE = bullseye
endif
ifeq ($(BR2_PACKAGE_SKELETON_DEBOOTSTRAP_DEBIAN_10_BUSTER_SUITE),y)
SKELETON_DEBOOTSTRAP_SUITE = buster
endif
ifeq ($(BR2_PACKAGE_SKELETON_DEBOOTSTRAP_DEBIAN_OLDOLDSTABLE_SUITE),y)
SKELETON_DEBOOTSTRAP_SUITE = oldoldstable
endif
ifeq ($(BR2_PACKAGE_SKELETON_DEBOOTSTRAP_DEBIAN_OLDSTABLE_SUITE),y)
SKELETON_DEBOOTSTRAP_SUITE = oldstable
endif
ifeq ($(BR2_PACKAGE_SKELETON_DEBOOTSTRAP_DEBIAN_STABLE_SUITE),y)
SKELETON_DEBOOTSTRAP_SUITE = stable
endif
ifeq ($(BR2_PACKAGE_SKELETON_DEBOOTSTRAP_DEBIAN_TESTING_SUITE),y)
SKELETON_DEBOOTSTRAP_SUITE = testing
endif
ifeq ($(BR2_PACKAGE_SKELETON_DEBOOTSTRAP_DEBIAN_UNSTABLE_SUITE),y)
SKELETON_DEBOOTSTRAP_SUITE = unstable
endif
ifeq ($(BR2_PACKAGE_SKELETON_DEBOOTSTRAP_CUSTOM_SUITE),y)
SKELETON_DEBOOTSTRAP_SUITE = $(call qstrip,$(BR2_PACKAGE_SKELETON_DEBOOTSTRAP_CUSTOM_SUITE_NAME))
ifeq ($(SKELETON_DEBOOTSTRAP_SUITE),)
$(error No custom suite name set. Check your BR2_PACKAGE_SKELETON_DEBOOTSTRAP_CUSTOM_SUITE_NAME setting)
endif
endif

SKELETON_DEBOOTSTRAP_MIRROR = $(call qstrip,$(BR2_PACKAGE_SKELETON_DEBOOTSTRAP_MIRROR))
SKELETON_DEBOOTSTRAP_SCRIPT = $(call qstrip,$(BR2_PACKAGE_SKELETON_DEBOOTSTRAP_SCRIPT))

SKELETON_DEBOOTSTRAP_ENV += IDO_SECURE_PATH=$(HOST_DIR)/bin:/usr/local/bin:/usr/bin:/bin
SKELETON_DEBOOTSTRAP_ENV += IAMROOT_EXEC_IGNORE="mountpoint|pam-auth-update|chfn"

# chfn: PAM: Critical error - immediate abort
# adduser: `/usr/bin/chfn -f systemd Network Management systemd-network' returned error code 1. Exiting.
SKELETON_DEBOOTSTRAP_ENV += IAMROOT_EXEC_IGNORE="mountpoint|pam-auth-update|chfn"
SKELETON_DEBOOTSTRAP_ENV += IAMROOT_PATH_RESOLUTION_IGNORE="^/(proc|sys)/|^/dev/(null|zero|full|random|urandom|tty|console|pts|shm|ptmx)"

define SKELETON_DEBOOTSTRAP_BUILD_CMDS
	rm -Rf $(@D)/rootfs
	PATH=$(BR_PATH) $(SKELETON_DEBOOTSTRAP_ENV) DEBOOTSTRAP_DIR=$(HOST_DIR)/share/debootstrap ido --multiarch debootstrap $(SKELETON_DEBOOTSTRAP_OPTS) $(SKELETON_DEBOOTSTRAP_SUITE) $(@D)/rootfs $(SKELETON_DEBOOTSTRAP_MIRROR) $(SKELETON_DEBOOTSTRAP_SCRIPT)
endef

define SKELETON_DEBOOTSTRAP_INSTALL_TARGET_CMDS
	$(call SYSTEM_RSYNC,$(@D)/rootfs,$(TARGET_DIR))
endef

$(eval $(generic-package))
